version: '3.9'

services:
  webcursos-app:
    build:
      context: .
      dockerfile: Dockerfile
    image: kaiquemgovani/kaiquemg:latest
    container_name: webcursos-app
    ports:
      - "8080:8080"
