# yaml-language-server: $schema=https://raw.githubusercontent.com/compose-spec/compose-spec/master/schema/compose-spec.json
version: "3.9"

services:
  webcursos:
    build: .
    image: webcursos:latest
    ports:
      - "8081:8081"
    environment:
      - JAVA_OPTS=-Xms256m -Xmx512m
    restart: unless-stopped
